name: 2D-RAFT-DIC
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.7.1
  - torchvision=0.22.1
  - torchaudio=2.7.1
  - pytorch-cuda=12.8
  - opencv
  - pillow
  - numpy
  - scipy
  - matplotlib
  - tifffile
